<?php 

/**
 * {@inheritdoc}
 */
function omdexam_menu() {
    $items = array();
  
    $items['admin/config/omdexa'] = array(
      'title' => 'ASS My Module',
      'description' => 'Whatever',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('my_module_admin_form'),
      'access arguments' => array('administer my module'),
      'type' => MENU_NORMAL_ITEM,
    );
    return $items;
  }